---
swagger: "2.0"
info:
  version: "1.0.1"
  title: "Swagger 2.0 Lambda from Swagger-Hub"
schemes:
- "https"
paths:
  /:
    get:
      operationId: "rootGET"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "200 response"
      x-swagger-router-controller: "Default"
definitions: {}
